name: Parse AESO CSVs

on:
  workflow_dispatch: # allows manual run
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run parser
        run: python parse_aeso_csvs.py

      - name: Commit output
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add monthly_data.csv
          git commit -m "Update monthly data" || echo "No changes to commit"
          git push
