name: Parse AESO CSVs

on:
  workflow_dispatch:  # run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Clone source CSV repo
        run: git clone https://github.com/intermittentnrg/intermittent-aeso-sns-sqs.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pandas

      - name: Run parser
        run: python parse_aeso_csvs.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add monthly_data
          git commit -m "Update monthly parsed data" || echo "No changes to commit"
          git push
